/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}", "./utils/**/*.{js,ts,jsx,tsx}"],
  plugins: [require("daisyui")],
  darkTheme: "dark",
  darkMode: ["selector", "[data-theme='dark']"],
  daisyui: {
    themes: [
      {
        light: {
          primary: "#4338ca",
          "primary-content": "#e0e7ff",
          secondary: "#DAE8FF",
          "secondary-content": "#212638",
          accent: "#93BBFB",
          "accent-content": "#212638",
          neutral: "#09090b",
          "neutral-content": "#e4e4e7",
          "base-100": "#ffffff",
          "base-200": "#f8f8f8",
          "base-300": "#eeeeee",
          "base-content": "#18181b",
          info: "#38bdf8",
          "info-content": "#082f49",
          success: "#34d399",
          "success-content": "#064e3b",
          warning: "#fbbf24",
          "warning-content": "#78350f",
          error: "#fb7185",
          "error-content": "#4c0519",
          "--rounded-btn": "9999rem",
          ".tooltip": { "--tooltip-tail": "6px" },
          ".link": { textUnderlineOffset: "2px" },
          ".link:hover": { opacity: "80%" },
        },
      },
      {
        dark: {
          primary: "#6366f1",
          "primary-content": "#eef2ff",
          secondary: "#323f61",
          "secondary-content": "#F9FBFF",
          accent: "#4969A6",
          "accent-content": "#F9FBFF",
          neutral: "#09090b",
          "neutral-content": "#e4e4e7",
          "base-100": "#262626",
          "base-200": "#1a1e24",
          "base-300": "#0a0a0a",
          "base-content": "#F9FBFF",
          info: "#38bdf8",
          "info-content": "#082f49",
          success: "#34d399",
          "success-content": "#064e3b",
          warning: "#fbbf24",
          "warning-content": "#78350f",
          error: "#fb7185",
          "error-content": "#4c0519",
          "--rounded-btn": "9999rem",
          ".tooltip": { "--tooltip-tail": "6px", "--tooltip-color": "oklch(var(--p))" },
          ".link": { textUnderlineOffset: "2px" },
          ".link:hover": { opacity: "80%" },
        },
      },
    ],
  },
  theme: {
    extend: {
      boxShadow: { center: "0 0 12px -2px rgb(0 0 0 / 0.05)" },
      animation: { "pulse-fast": "pulse 1s cubic-bezier(0.4, 0, 0.6, 1) infinite" },
    },
  },
  safelist: [
    "bg-sky-200",
    "bg-sky-400",
    "text-sky-800",
    "bg-emerald-200",
    "bg-emerald-400",
    "text-emerald-800",
    "bg-gray-200",
    "bg-gray-400",
    "text-gray-800",
    "bg-rose-200",
    "bg-rose-400",
    "text-rose-800",
    "bg-green-200",
    "bg-green-400",
    "text-green-800",
    "bg-indigo-200",
    "bg-indigo-400",
    "text-indigo-800",
    "bg-amber-200",
    "bg-amber-400",
    "text-amber-800",
    "bg-violet-200",
    "bg-violet-400",
    "text-violet-800",
    "bg-teal-200",
    "bg-teal-400",
    "text-teal-800",
  ],
};
